pipeline {
    agent any
    stages {
        stage('Newman Tests') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){
                    sh '''
                    node --version
                    cd api/newman
                    newman run ExamenManuelChinchilla.postman_collection.json -e envExamManuelChinchilla.postman_environment.json
                    cd ..
                    cd ..
                    '''
                }
            }
        }
        stage('Rest Assured Tests') {
                steps {
                    catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){
                        sh '''
                        cd api/rest_assured
                        mvn clean test
                        cd ..
                        cd ..
                        '''
                    }
                }
        }
        stage('jMeter Tests') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){
                    sh '''
                    cd load
                    jmeter -n -t examen_test_plan.jmx
                    '''
                }
            }
        }
    }
}
